---
title: "Main experiment regression modeling"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
options(width=1200)
fig_text_sz <- 14

# create results folder if it doesn't exist
resFolder <- paste0("./Results/results",format(Sys.time(),'_%Y%m%d'))
if (!dir.exists(file.path(resFolder))) {dir.create(file.path(resFolder), recursive=T)}

# load packages
pacman::p_load(report, ggplot2, ggeffects, grid, gridExtra, 
               rgl, dplyr, RColorBrewer, lmerTest, broom)
```

```{r data}
# Note that pre-experiment: exp1 and main experiment: exp2 in naming
# read in data, 
df <- read.csv('../Data/df_regression_exp2.csv')

# update column names
colnames(df) <- c('item_dissimilarity_exp2',
                  'condition',
                  'category',
                  'subcategory'
                  ,'color_disp',
                  'large_disp',
                  'differences',
                  'diffs_demeaned',
                  'exp2_feature_dissim_demeaned',
                  'exp1_feature_dissim_demeaned',
                  'correlation',
                  'distance')

# factor variables
df$category <- factor(df$category,
                      levels = c(0,1),
                      labels = c('same','different'))
df$subcategory <- factor(df$subcategory,
                         levels = c(0,1), 
                         labels =c('same','different'))
df$condition <- factor(df$condition,
                       levels = c(0,1), 
                       labels = c('color','large'))

## absolute and z-score
df$color_disp    <- abs(df$color_disp)
df$large_disp    <- abs(df$large_disp)
df$item_dissimilarity_exp2 <- scale(df$item_dissimilarity_exp2)
df$differences   <- scale(df$differences)

summary(df)
```

```{r modeling_01}
#  condition & category
mod1 <- lm(item_dissimilarity_exp2~condition,df)
summary(mod1)
mod2 <- lm(item_dissimilarity_exp2~condition*category,df)
summary(mod2)
anova(mod1,mod2)

# entering category first to be sure 
mod3 <- lm(item_dissimilarity_exp2~category,df)
summary(mod3)
mod4 <- lm(item_dissimilarity_exp2~category*condition,df)
summary(mod4)
anova(mod3,mod4)

# subcategory
mod5 <- lm(item_dissimilarity_exp2~subcategory,df)
summary(mod5)
mod6 <- lm(item_dissimilarity_exp2~subcategory*condition,df)
summary(mod6)
anova(mod5,mod6)

# color
mod7 <- lm(item_dissimilarity_exp2~category*color_disp,df)
summary(mod7)
anova(mod3,mod7)

# large
mod8 <- lm(item_dissimilarity_exp2~category*large_disp,df)
summary(mod8)
anova(mod3,mod8)
```

```{r modeling_02}
## learning induced shifts in item similarity representations
mod9 <- lm(item_dissimilarity_exp2~category*color_disp*large_disp,df)
summary(mod9)
anova(mod7,mod9)
anova(mod8,mod9)
report_effectsize(mod9)

# partial eta^2
mod9.aov <- anova(mod9)
mod9.peta <- list()
mod9.peta[1] <- mod9.aov$`Sum Sq`[1]/sum(mod9.aov$`Sum Sq`)
mod9.peta[2] <- mod9.aov$`Sum Sq`[2]/sum(mod9.aov$`Sum Sq`)
mod9.peta[3] <- mod9.aov$`Sum Sq`[3]/sum(mod9.aov$`Sum Sq`)
mod9.peta[4] <- mod9.aov$`Sum Sq`[4]/sum(mod9.aov$`Sum Sq`)
mod9.peta[5] <- mod9.aov$`Sum Sq`[5]/sum(mod9.aov$`Sum Sq`)

# for visualization, create factor variable from distribution of large_disp values
m <- mean(df$large_disp)
s <- sd(df$large_disp)

# five levels
bounds <- c(m-2*s,m-s,m+s,m+2*s)  # standard deviations
newdf <- df %>%
  mutate(., large_disp = with(., case_when(
    (large_disp < bounds[1]) ~ '< 2sd',
    (large_disp < bounds[2] & large_disp > bounds[1]) ~ '< 1sd',
    (large_disp < bounds[3] & large_disp > bounds[2]) ~ '+/- 1sd',
    (large_disp > bounds[3] & large_disp < bounds[4]) ~ '> 1sd',
    (large_disp > bounds[4]) ~ '> 2sd',
    is.na(large_disp) ~ 'na',
    TRUE ~ 'na'
  )))

# median split
newdf <- df %>%
  mutate(., large_disp = with(., case_when(
    (large_disp < median(large_disp)) ~ 'below median',
    (large_disp >= median(large_disp)) ~ 'above median',
    is.na(large_disp) ~ 'na',
    TRUE ~ 'na'
  )))

# three levels
bounds2 <- c(m-1.5*s,m+1.5*s)  #standard deviations
newdf <- df %>%
  mutate(., large_disp = with(., case_when(
    (large_disp < bounds2[1]) ~ '< 1.5 sd',
    (large_disp > bounds2[1] & large_disp <= bounds2[2]) ~ '+/- 1.5 sd',
    (large_disp > bounds2[2]) ~ '> 1.5 sd',
    is.na(large_disp) ~ 'na',
    TRUE ~ 'na'
  )))

# visualize
ggplot(newdf,aes(color_disp,item_dissimilarity_exp2,color=large_disp)) +
  geom_point(alpha=.5) +
  facet_wrap(~category) +
  scale_color_manual(values=c("indianred", "forestgreen", "blue")) +
  theme(text=element_text(size=20),
        plot.title = element_text(hjust = 0.5)) +
  xlab('color rating disparity') +
  ggtitle('color*large*category interaction') +
  labs(colour='large rating \ndisparity')

```

```{r modeling_03}
# difference modeling
mod10 <- lm(differences~condition,df)
summary(mod10)
mod11 <- lm(differences~condition*category,df)
summary(mod11)
anova(mod10,mod11)

# entering backwards just for checking
mod12 <- lm(differences~category,df)
summary(mod12)
mod13 <- lm(differences~category*condition,df)
summary(mod13)
anova(mod12,mod13)

# subcategory
mod14 <- lm(differences~subcategory,df)
summary(mod14)
mod15 <- lm(differences~subcategory*condition,df)
summary(mod15)
anova(mod14,mod15)

# ratings
mod16 <- lm(differences~condition*category*color_disp,df)
summary(mod16)
anova(mod11,mod16)
mod17 <- lm(differences~condition*category*large_disp,df)
summary(mod17)
anova(mod11,mod17)

## without category and condition
mod18 <- lm(differences~color_disp,df)
summary(mod18)
mod19 <- lm(differences~color_disp*large_disp,df)
summary(mod19)
report_effectsize(mod19)
anova(mod18,mod19)
mod20 <- lm(differences~large_disp,df)
summary(mod20)
mod21 <- lm(differences~large_disp*color_disp,df)
summary(mod21)
anova(mod20,mod21)

# visualize
ggplot(newdf,aes(color_disp,differences,color=large_disp)) +
  geom_point(alpha=.5) +
  scale_color_manual(values=c("indianred", "forestgreen", "blue")) +
  theme(text=element_text(size=20),
        plot.title = element_text(hjust = 0.5)) +
  xlab('color rating disparity') +
  ylab('differences in\ndissimilarity') +
  ggtitle('color*large interaction') +
  labs(colour='large rating \ndisparity')

# interaction
df.clr <- subset(df,df$condition=='color')
df.lrg <- subset(df,df$condition=='large')

# checking just dissim
dis.clr <- lm(item_dissimilarity_exp2~category*color_disp,df.clr)
summary(dis.clr)
dis.lrg <- lm(item_dissimilarity_exp2~category*large_disp,df.lrg)
summary(dis.lrg)
dis1 <- lm(item_dissimilarity_exp2~category*large_disp,df)
summary(dis1)

# differences
mod.full <- lm(differences~category*color_disp*large_disp,df)
summary(mod.full)
mod.full2 <- lm(differences~color_disp*large_disp,df)
summary(mod.full2)
report_effectsize(mod.full2)
mod.clr <- lm(differences~category*color_disp,df.clr)
summary(mod.clr)
report_effectsize(mod.clr)
mod.lrg <- lm(differences~category*large_disp,df.lrg)
summary(mod.clr)
report_effectsize(mod.lrg)
```


```{r modeling_demeaned}
# demeaning
# from above
mod.clr.demeaned <- lm(diffs_demeaned~category*color_disp,df.clr)
summary(mod.clr.demeaned)
mod.lrg.demeaned <- lm(diffs_demeaned~category*large_disp,df.lrg)
summary(mod.lrg.demeaned)
report_effectsize(mod.clr.demeaned)
report_effectsize(mod.lrg.demeaned)
```

```{r response_to_reviewers}
# Note that pre-experiment: exp1 and main experiment: exp2 in naming
# exp2_dissim ~ exp1_dissim
# exp2_dissim ~ exp1_dissim + disparities
df$disparities <- c(df$color_disp[df$condition=='color'],
                    df$large_disp[df$condition=='large'])

# together
m1 <- lm(exp2_feature_dissim_demeaned~exp1_feature_dissim_demeaned,df)
summary(m1)
report_effectsize(m1)
m2 <- lm(exp2_feature_dissim_demeaned~exp1_feature_dissim_demeaned*disparities,df)
summary(m2)
report_effectsize(m2)
anova(m1,m2)

# same category
df.same.cat <- subset(df,df$category=='same')
m3 <- lm(exp2_feature_dissim_demeaned~exp1_feature_dissim_demeaned,df.same.cat)
summary(m3)
report_effectsize(m3)
m4 <- lm(exp2_feature_dissim_demeaned~exp1_feature_dissim_demeaned*disparities,df.same.cat)
summary(m4)
report_effectsize(m4)
anova(m3,m4)

# same subcategory
df.same.subcat <- subset(df,df$subcategory=='same')
m5 <- lm(exp2_feature_dissim_demeaned~exp1_feature_dissim_demeaned,df.same.subcat)
summary(m5)
report_effectsize(m5)
m6 <- lm(exp2_feature_dissim_demeaned~exp1_feature_dissim_demeaned*disparities,df.same.subcat)
summary(m6)
report_effectsize(m6)
anova(m5,m6)

# model details
lapply(list(m1,m2,m3,m4,m5,m6),glance)

# updating with category regressor
df$recat <- df$category=='same'
df$resubcat <- df$subcategory=='same'
m7 <- lm(exp2_feature_dissim_demeaned ~ exp1_feature_dissim_demeaned,df)
summary(m7)
report_effectsize(m7)
m8 <- lm(exp2_feature_dissim_demeaned ~ exp1_feature_dissim_demeaned * category, df)
summary(m8)
report_effectsize(m8)
anova(m7,m8)
m9 <- lm(exp2_feature_dissim_demeaned ~ exp1_feature_dissim_demeaned * recat * disparities, df)
summary(m9)
report_effectsize(m9)
m9.aov <- anova(m9)
m9.aov$`Sum Sq`
m9.peta <- list()
m9.peta[1] <- m9.aov$`Sum Sq`[1] / sum(m9.aov$`Sum Sq`)
m9.peta[2] <- m9.aov$`Sum Sq`[7] / sum(m9.aov$`Sum Sq`)
anova(m8,m9)

# model details
lapply(list(m7,m8,m9),glance)

# udating with subcategory regressor
m10 <- lm(exp2_feature_dissim_demeaned ~ exp1_feature_dissim_demeaned * resubcat, df)
summary(m10)
report_effectsize(m10)
anova(m7,m10)
m11 <- lm(exp2_feature_dissim_demeaned ~ exp1_feature_dissim_demeaned * resubcat * disparities, df)
summary(m11)
anova(m10,m11)

# model details
lapply(list(m10,m11),glance)
```

